seed: 42

# Optimizer
optimizer:
  name: "adam"
  lr: 1e-3
  weight_decay: 1e-4
  betas: [0.9, 0.999]

# Learning rate scheduler
scheduler:
  name: "reduce_on_plateau"
  mode: "min"
  factor: 0.5
  patience: 10
  min_lr: 1e-6

# Training
batch_size: 128
num_epochs: 100
early_stopping_patience: 20
early_stopping_monitor: "val_loss"
early_stopping_mode: "min"

# Hardware
accelerator: "cpu"
devices: 1
num_workers: 4
pin_memory: false

# Mixed precision (disabled for CPU)
precision: 32

# Checkpointing
save_top_k: 1
monitor: "val_loss"
mode: "min"
save_last: true

# Validation
val_check_interval: 1.0
check_val_every_n_epoch: 1

# Logging
log_every_n_steps: 10
enable_progress_bar: true

# Reproducibility
deterministic: true